export const customTemplateAttribute01 = {
  active: true,
  attributable_type: "existing_lighting",
  code_name: "ballast_factor",
  company_template_id: 1,
  default_value: null,
  description: null,
  display_order: null,
  edited: false,
  hint: "",
  input_type: "list",
  label: "Ballast Factor",
  locked: null,
  mobile_id: 1,
  mobile_project_id: null,
  name: "Ballast Factor",
  placeholder: "select",
  project_id: null,
  required_for_calculations: null,
  required_to_complete: false,
  server_id: 63,
  short_name: null,
  tab: "primary",
  unit: null,
  unit_position: null,
}

export const customTemplateAttribute02 = {
  active: true,
  attributable_type: "existing_lighting",
  code_name: "difficulty_factor",
  company_template_id: 1,
  default_value: null,
  description: null,
  display_order: null,
  edited: false,
  hint: "",
  input_type: "list",
  label: "Difficulty Factor",
  locked: null,
  mobile_id: 2,
  mobile_project_id: null,
  name: "Difficulty Factor",
  placeholder: "select",
  project_id: null,
  required_for_calculations: null,
  required_to_complete: false,
  server_id: 63,
  short_name: null,
  tab: "primary",
  unit: null,
  unit_position: null,
}

export const projectCustomTemplateAttribute01 = {
  active: true,
  attributable_type: "project",
  code_name: "project_difficulty_factor",
  company_template_id: 1,
  default_value: null,
  description: null,
  display_order: null,
  edited: false,
  hint: "",
  input_type: "integer",
  label: "Project Difficulty Factor",
  locked: null,
  mobile_id: 2,
  mobile_project_id: null,
  name: "Project Difficulty Factor",
  required_for_calculations: null,
  required_to_complete: false,
  server_id: 65,
  short_name: null,
  tab: "primary",
  unit: null,
  unit_position: null,
}

export const areaCustomTemplateAttribute01 = {
  active: true,
  attributable_type: "area",
  code_name: "area_attribute",
  company_template_id: 1,
  default_value: null,
  description: null,
  display_order: null,
  edited: false,
  hint: "",
  input_type: "integer",
  label: "Area Attribute",
  locked: null,
  mobile_id: 2,
  mobile_project_id: null,
  name: "Area Attribute",
  required_for_calculations: null,
  required_to_complete: false,
  server_id: 64,
  short_name: null,
  tab: "primary",
  unit: null,
  unit_position: null,
}

export const customTemplateAttributes = [customTemplateAttribute01, customTemplateAttribute02, projectCustomTemplateAttribute01, areaCustomTemplateAttribute01]
